### PR TITLE
Added baryon output and fixed k-output mode

### PR DESCRIPTION
**Pull request by ThomasTram**
Add 5-year old tweaks to SONG (including baryon output)

### CODE REVIEW

**Comment by ThomasTram** [comment]
Ah sorry, I don't know if this PR is ready for the main song repository. It was meant for my own fork, but I am leaving it here just in case...

**Comment by ThomasTram** [comment]
And there is also a bug...

**Comment by coccoinomane** [comment]
Haha ciao Thomas, nice to hear from you 😄
How are you doing?
Feel free to modify the original SONG, I'll make you admin of the repo!
PS: For any need my email is guido.pettinari@gmail.com

**Comment by coccoinomane** [comment]
@ThomasTram

**Comment by ThomasTram** [comment]
Hi @coccoinomane , didn't know you still followed SONG! I hope you are doing well? I actually spent a year working as a software developer before returning to academia in a permanent position at Aarhus University. I have translated CLASS into C++ (https://github.com/AarhusCosmology/CLASSpp_public) and we have a nice setup with issue-tracking and automated testing. If I/we find the time, we should do SONG++! 😄 

Cheers,
Thomas

**Comment by coccoinomane** [comment]
Good for you @ThomasTram ! Happy to hear you landed a permanent position :-)

I am still working at the web agency in Rome and am now dipping my toe in blockchain/crypto tech.

As for C++... I haven't developed masochistic tendences yet, so I wouldn't dream of converting SONG to another programming language 😜  But feel free to edit/improve the code as you deem most useful.

And most importantly: let me know if you visit Rome, we need to catch up in front of a nice Carbonara & red wine!

Cheers,
Guido

**Comment by ChristianFidler** [comment]
Hi Guido,

nice to hear from you. Maybee I can come to visit Rome at some point though it will probably be 2023 since we are getting another baby after Christmas.
I have been following crypto for a few years and did some smaller hobby projects. What are your plans? Is it related to your work in the web agency?

Best wishes, Christian

**Comment by coccoinomane** [comment]
@ChristianFidler 
Ciao Christian!!! I love this Github thread, so good to hear from you guys
Congratulation to you and Melanie for the next arrival, it is great news! You need to tell me what number of kids you're speaking about, I left you at two I think...
I didn't know you were a crypto veteran! I have started to learn in January this year and invested something, not related to the web agency but just for passion and education. I would love to chat about it, hit me on Telegram (coccoinomane) if you want too :-)

**Pull request closed without merging**
